2015-11-26 17:47:33,960 -INFO:    loading a new bench:bench.csv
2015-11-26 17:47:33,963 -INFO:    releasing duts in old dut_pool
2015-11-26 17:47:33,964 -INFO:    loading case: 1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.050_EX24_0003-2.4.50.3
2015-11-26 17:47:35,648 -INFO:    starting to run case: cr.py upgradeE7.csv bench.csv full N6 e7 e7 600 E7_R02.04.050_EX24_0003 2.4.50.3
2015-11-26 17:47:35,650 -INFO:    starting segment:0
2015-11-26 17:48:08,039 -ERROR:    Case FAIL
2015-11-26 17:48:08,039 -ERROR:    
*********************************ERROR DUMP************************************
*logAction dump:
*	Function Name: 		run
*	Arguments: 		
*		1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.050_EX24_0003-2.4.50.3
*		{'N6': <e7.e7 object at 0x02B854F0>}
*		[[['N6', 'set session page dis tim dis', 'success: session updated.', '10', 10], ['N6', 'show alarm', '>', '60', 11], ['N6', 'upgrade  system  server  10.245.3.201 user  e7 directory-path E7_R02.04.050_EX24_0003 version 2.4.50.3 ', 'Password:', '10', 12], ['N6', 'e7', 'Software Upgrade in progress -- Version=2.4.50.3', '40', 13], ['N6', '', 'no:Upgrade: Had Errors', '30', 14], ['N6', 'try 2:show upgrade', 'NO:failed', '60', 15], ['N6', 'try 600:show upgrade', 'upgrade performed', '60', 16], ['N6', 'show card', '>', '30', 17], ['N6', 'show version', '>', '30', 18], ['N6', 'setAutoReloginFlag(1)', '', '0', 19], ['N6', 'reset system version  2.4.50.3', 'yes/no', '30', 20], ['N6', 'yes', 'Reset: In Progress -- Version=2.4.50.3', '30', 21], ['N6', 'SLEEP(300)', '', '0', 22], ['N6', 'try 3:set session page dis tim dis', 'success: session updated.', '10', 23], ['N6', 'show alarm', '>', '60', 24], ['N6', 'show version', '>', '20', 25], ['N6', 'try 180:show card detail', 'Alarms:\\s*\r*\n\\s*<none>\\s*\r*\n\\s*Conditions:\\s*\r*\n\\s*Release is not Committed.+Alarms:\\s*\r*\n\\s*<none>\\s*\r*\n\\s*Conditions:\\s*\r*\n\\s*Release is not Committed', '30', 26], ['N6', 'try 2:commit system version 2.4.50.3', 'no:failed', '30', 27], ['N6', 'show version', '>', '30', 28], ['N6', 'show alarm', '>', '30', 29]], [], []]
*		full
*		<logging.Logger object at 0x02B66990>
*	Keyword Arguments: 		
*-------------------------------------------------------------------------------
*ERROR MESSAGE:
*   tried 1 time(s), failed in function(singleStep),
*	arg( ['', 'Upgrade: Had Errors', '30', False, True, False])
*	kwarg ({})
*
*Exception:pattern(Upgrade: Had Errors) found with 30.000000, buffer is:
*--buffer start--
*
*N6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:
*    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"
*EVENT for system at 2015/11/26 17:53:08.99:
*    "Upgrade: Had Errors -- Version=2.4.50.3"
*Alarm CLEARED for system at 2015/11/26 17:53:08.99:
*    "Software Upgrade in progress"
*
*--buffer end here--
*
*
*Traceback (most recent call last):
*  File "C:\workspace\idash\lib\runner.py", line 18, in inner
*    response = fun(*arg, **kwargs)
*  File "C:\workspace\idash\lib\runner.py", line 210, in run
*    runSegment(casename, mode, modeset[index], duts,seqlist[index],  segNamelist[index], logger)
*  File "C:\workspace\idash\lib\runner.py", line 191, in runSegment
*    session.stepCheck(casename, lineno, cmd, expect, due)
*  File "C:\workspace\idash\lib\dut.py", line 298, in stepCheck
*    retry(CaseName, int(MaxTry), FunName, ListArg, DicArg)
*  File "C:\workspace\idash\lib\dut.py", line 294, in retry
*    raise ValueError('tried %d time(s), failed in function(%s),\n\targ( %s)\n\tkwarg (%s)\n\nException:%s\n'%(counter, fun.func_name, str(arg), str(kwarg),errormessage))
*ValueError: tried 1 time(s), failed in function(singleStep),
*	arg( ['', 'Upgrade: Had Errors', '30', False, True, False])
*	kwarg ({})
*
*Exception:pattern(Upgrade: Had Errors) found with 30.000000, buffer is:
*--buffer start--
*
*N6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:
*    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"
*EVENT for system at 2015/11/26 17:53:08.99:
*    "Upgrade: Had Errors -- Version=2.4.50.3"
*Alarm CLEARED for system at 2015/11/26 17:53:08.99:
*    "Software Upgrade in progress"
*
*--buffer end here--
*
*
*-------------------------------------------------------------------------------
*globals=>
*	'__author__': 'Sean Yu'
*	'__doc__': None
*	'__file__': 'C:\workspace\idash\lib\dut.pyc'
*	'__name__': 'dut'
*	'__package__': None
*	'dut': <class 'dut.dut'>
*	'time': <module 'time' (built-in)>
*
*locals =>
*	'FunName': 'singleStep'
*	'GetFunctionbyName': <function GetFunctionbyName at 0x02B12CB0>
*	'IsFail': True
*	'arg': ['', 'Upgrade: Had Errors', '30', False, True, False]
*	'casename': '1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.050_EX24_0003-2.4.50.3'
*	'counter': 1
*	'e': RuntimeError('pattern(Upgrade: Had Errors) found with 30.000000, buffer is:\n--buffer start--\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n\n--buffer end here--\n',)
*	'errormessage': 'pattern(Upgrade: Had Errors) found with 30.000000, buffer is:\n--buffer start--\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n\n--buffer end here--\n'
*	'fun': <bound method e7.singleStep of <e7.e7 object at 0x02B854F0>>
*	'funName': 'singleStep'
*	'kwarg': {}
*	'maxtry': 1
*	'self': <e7.e7 object at 0x02B854F0>
*		'_has_poll': False
*		'attribute': {'PROMPT': '>|#|>>>', 'LOGIN': '../bench/e7.login', 'SUT': 'e7', 'CMD': 'telnet 10.245.3.19'}
*		'cookedq': ':\r\n    "Software Upgrade in progress"\r\n'
*		'debuglevel': 0
*		'eof': False
*		'host': '10.245.3.19'
*		'iacseq': ''
*		'idxSearch': 1644
*		'idxUpdate': 1426
*		'irawq': 0
*		'lockRelogin': <thread.lock object at 0x021BD950>
*		'lockStreamOut': <thread.lock object at 0x021BD970>
*		'logfile': <open file 'C:\workspace\idash\test\log\st_dhcpv6-csv-2-3-E7_R02-04-050_EX24_0003-2-4-50-3-201511261-2015-11-26_174649.347000\1-2015-11-26_174733.940000\1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.-2015-11-26_174733.948000\N6.log', mode 'wb' at 0x02B6F5F8>
*		'logger': <logging.Logger object at 0x02B178F0>
*		'loginDone': True
*		'name': 'N6'
*		'option_callback': None
*		'port': 23
*		'rawq': ''
*		'sb': 0
*		'sbdataq': ''
*		'sock': <socket._socketobject object at 0x02B15998>
*		'streamOut': '"N6" Thu Nov 26 17:53:02 2015\n\r\nUsername: \r\nUsername: e7support\r\nPassword: \r\nN6>set ses time dis page dis\r\nsuccess: session updated.\r\nN6>set session page dis tim dis\r\nsuccess: session updated.\r\nN6>show alarm\r\nOccurred Time          Severity Alarm                                          \r\n---------------------- -------- -----------------------------------------------\r\n2015/11/25 15:43:30.02 minor    Ethernet port "1/2/g1"\r\n                                "Improper removal"\r\n                                 (affects service)\r\n\r\n1 alarm found.\r\nN6>upgrade  system  server  10.245.3.201 user  e7 directory-path E7_R02.04.\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$ystem  server  10.245.3.201 user  e7 directory-path E7_R02.04.0          \x08\x08\x08\x08\x08\x08\x08\x08\x08\x0850_EX24_0\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$ver  10.245.3.201 user  e7 directory-path E7_R02.04.050_EX24_00           \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x0803 versio\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$5.3.201 user  e7 directory-path E7_R02.04.050_EX24_0003 version           \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08 2.4.50.3\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$er  e7 directory-path E7_R02.04.050_EX24_0003 version 2.4.50.3            \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\r\nPassword: \r\nN6>warning ALARM for system at 2015/11/26 17:53:05.99:\r\n    "Software Upgrade in progress -- Version=2.4.50.3 (No auto-reset)"\r\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n'
*		'timeout': 0.5
*		'timestampCmd': 1448531258.119
*	'traceback': <module 'traceback' from 'C:\Python27\lib\traceback.pyc'>
*
**********************************EREOR END*************************************


Traceback (most recent call last):
  File "C:\workspace\idash\lib\runner.py", line 468, in run1case
    returncode, STRerrormessage= case_runner(casename,dut_pool,seq, case_mode, caselogger)
  File "C:\workspace\idash\lib\runner.py", line 229, in case_runner
    caseFail, errorMessage = run(casename, dictDUTs, case_seq, m, logger)
  File "C:\workspace\idash\lib\runner.py", line 36, in inner
    raise Exception(msg)
Exception: 
*********************************ERROR DUMP************************************
*logAction dump:
*	Function Name: 		run
*	Arguments: 		
*		1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.050_EX24_0003-2.4.50.3
*		{'N6': <e7.e7 object at 0x02B854F0>}
*		[[['N6', 'set session page dis tim dis', 'success: session updated.', '10', 10], ['N6', 'show alarm', '>', '60', 11], ['N6', 'upgrade  system  server  10.245.3.201 user  e7 directory-path E7_R02.04.050_EX24_0003 version 2.4.50.3 ', 'Password:', '10', 12], ['N6', 'e7', 'Software Upgrade in progress -- Version=2.4.50.3', '40', 13], ['N6', '', 'no:Upgrade: Had Errors', '30', 14], ['N6', 'try 2:show upgrade', 'NO:failed', '60', 15], ['N6', 'try 600:show upgrade', 'upgrade performed', '60', 16], ['N6', 'show card', '>', '30', 17], ['N6', 'show version', '>', '30', 18], ['N6', 'setAutoReloginFlag(1)', '', '0', 19], ['N6', 'reset system version  2.4.50.3', 'yes/no', '30', 20], ['N6', 'yes', 'Reset: In Progress -- Version=2.4.50.3', '30', 21], ['N6', 'SLEEP(300)', '', '0', 22], ['N6', 'try 3:set session page dis tim dis', 'success: session updated.', '10', 23], ['N6', 'show alarm', '>', '60', 24], ['N6', 'show version', '>', '20', 25], ['N6', 'try 180:show card detail', 'Alarms:\\s*\r*\n\\s*<none>\\s*\r*\n\\s*Conditions:\\s*\r*\n\\s*Release is not Committed.+Alarms:\\s*\r*\n\\s*<none>\\s*\r*\n\\s*Conditions:\\s*\r*\n\\s*Release is not Committed', '30', 26], ['N6', 'try 2:commit system version 2.4.50.3', 'no:failed', '30', 27], ['N6', 'show version', '>', '30', 28], ['N6', 'show alarm', '>', '30', 29]], [], []]
*		full
*		<logging.Logger object at 0x02B66990>
*	Keyword Arguments: 		
*-------------------------------------------------------------------------------
*ERROR MESSAGE:
*   tried 1 time(s), failed in function(singleStep),
*	arg( ['', 'Upgrade: Had Errors', '30', False, True, False])
*	kwarg ({})
*
*Exception:pattern(Upgrade: Had Errors) found with 30.000000, buffer is:
*--buffer start--
*
*N6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:
*    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"
*EVENT for system at 2015/11/26 17:53:08.99:
*    "Upgrade: Had Errors -- Version=2.4.50.3"
*Alarm CLEARED for system at 2015/11/26 17:53:08.99:
*    "Software Upgrade in progress"
*
*--buffer end here--
*
*
*Traceback (most recent call last):
*  File "C:\workspace\idash\lib\runner.py", line 18, in inner
*    response = fun(*arg, **kwargs)
*  File "C:\workspace\idash\lib\runner.py", line 210, in run
*    runSegment(casename, mode, modeset[index], duts,seqlist[index],  segNamelist[index], logger)
*  File "C:\workspace\idash\lib\runner.py", line 191, in runSegment
*    session.stepCheck(casename, lineno, cmd, expect, due)
*  File "C:\workspace\idash\lib\dut.py", line 298, in stepCheck
*    retry(CaseName, int(MaxTry), FunName, ListArg, DicArg)
*  File "C:\workspace\idash\lib\dut.py", line 294, in retry
*    raise ValueError('tried %d time(s), failed in function(%s),\n\targ( %s)\n\tkwarg (%s)\n\nException:%s\n'%(counter, fun.func_name, str(arg), str(kwarg),errormessage))
*ValueError: tried 1 time(s), failed in function(singleStep),
*	arg( ['', 'Upgrade: Had Errors', '30', False, True, False])
*	kwarg ({})
*
*Exception:pattern(Upgrade: Had Errors) found with 30.000000, buffer is:
*--buffer start--
*
*N6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:
*    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"
*EVENT for system at 2015/11/26 17:53:08.99:
*    "Upgrade: Had Errors -- Version=2.4.50.3"
*Alarm CLEARED for system at 2015/11/26 17:53:08.99:
*    "Software Upgrade in progress"
*
*--buffer end here--
*
*
*-------------------------------------------------------------------------------
*globals=>
*	'__author__': 'Sean Yu'
*	'__doc__': None
*	'__file__': 'C:\workspace\idash\lib\dut.pyc'
*	'__name__': 'dut'
*	'__package__': None
*	'dut': <class 'dut.dut'>
*	'time': <module 'time' (built-in)>
*
*locals =>
*	'FunName': 'singleStep'
*	'GetFunctionbyName': <function GetFunctionbyName at 0x02B12CB0>
*	'IsFail': True
*	'arg': ['', 'Upgrade: Had Errors', '30', False, True, False]
*	'casename': '1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.050_EX24_0003-2.4.50.3'
*	'counter': 1
*	'e': RuntimeError('pattern(Upgrade: Had Errors) found with 30.000000, buffer is:\n--buffer start--\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n\n--buffer end here--\n',)
*	'errormessage': 'pattern(Upgrade: Had Errors) found with 30.000000, buffer is:\n--buffer start--\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n\n--buffer end here--\n'
*	'fun': <bound method e7.singleStep of <e7.e7 object at 0x02B854F0>>
*	'funName': 'singleStep'
*	'kwarg': {}
*	'maxtry': 1
*	'self': <e7.e7 object at 0x02B854F0>
*		'_has_poll': False
*		'attribute': {'PROMPT': '>|#|>>>', 'LOGIN': '../bench/e7.login', 'SUT': 'e7', 'CMD': 'telnet 10.245.3.19'}
*		'cookedq': ':\r\n    "Software Upgrade in progress"\r\n'
*		'debuglevel': 0
*		'eof': False
*		'host': '10.245.3.19'
*		'iacseq': ''
*		'idxSearch': 1644
*		'idxUpdate': 1426
*		'irawq': 0
*		'lockRelogin': <thread.lock object at 0x021BD950>
*		'lockStreamOut': <thread.lock object at 0x021BD970>
*		'logfile': <open file 'C:\workspace\idash\test\log\st_dhcpv6-csv-2-3-E7_R02-04-050_EX24_0003-2-4-50-3-201511261-2015-11-26_174649.347000\1-2015-11-26_174733.940000\1-cr.py-upgradeE7.csv-bench.csv-full-N6-e7-e7-600-E7_R02.04.-2015-11-26_174733.948000\N6.log', mode 'wb' at 0x02B6F5F8>
*		'logger': <logging.Logger object at 0x02B178F0>
*		'loginDone': True
*		'name': 'N6'
*		'option_callback': None
*		'port': 23
*		'rawq': ''
*		'sb': 0
*		'sbdataq': ''
*		'sock': <socket._socketobject object at 0x02B15998>
*		'streamOut': '"N6" Thu Nov 26 17:53:02 2015\n\r\nUsername: \r\nUsername: e7support\r\nPassword: \r\nN6>set ses time dis page dis\r\nsuccess: session updated.\r\nN6>set session page dis tim dis\r\nsuccess: session updated.\r\nN6>show alarm\r\nOccurred Time          Severity Alarm                                          \r\n---------------------- -------- -----------------------------------------------\r\n2015/11/25 15:43:30.02 minor    Ethernet port "1/2/g1"\r\n                                "Improper removal"\r\n                                 (affects service)\r\n\r\n1 alarm found.\r\nN6>upgrade  system  server  10.245.3.201 user  e7 directory-path E7_R02.04.\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$ystem  server  10.245.3.201 user  e7 directory-path E7_R02.04.0          \x08\x08\x08\x08\x08\x08\x08\x08\x08\x0850_EX24_0\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$ver  10.245.3.201 user  e7 directory-path E7_R02.04.050_EX24_00           \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x0803 versio\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$5.3.201 user  e7 directory-path E7_R02.04.050_EX24_0003 version           \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08 2.4.50.3\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08$er  e7 directory-path E7_R02.04.050_EX24_0003 version 2.4.50.3            \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\r\nPassword: \r\nN6>warning ALARM for system at 2015/11/26 17:53:05.99:\r\n    "Software Upgrade in progress -- Version=2.4.50.3 (No auto-reset)"\r\n\r\nN6>EVENT for card 1/1 at 2015/11/26 17:53:07.49:\r\n    "Upgrade: Failed File Xfer --  Reason: Software package does not have files for this card"\r\nEVENT for system at 2015/11/26 17:53:08.99:\r\n    "Upgrade: Had Errors -- Version=2.4.50.3"\r\nAlarm CLEARED for system at 2015/11/26 17:53:08.99:\r\n    "Software Upgrade in progress"\r\n'
*		'timeout': 0.5
*		'timestampCmd': 1448531258.119
*	'traceback': <module 'traceback' from 'C:\Python27\lib\traceback.pyc'>
*
**********************************EREOR END*************************************



